---

- name: main operation
  block:
    - name: obtain SSO token with using username/password credentials
      ovirt.ovirt.ovirt_auth:
        url: "{{ lookup('env', 'OVIRT_URL') | default(ovirt.url, true) }}"
        username: "{{ lookup('env', 'OVIRT_USERNAME') | default(ovirt.username, true) }}"
        password: "{{ lookup('env', 'OVIRT_PASSWORD') | default(ovirt.password, true) }}"
        insecure: true

    - name: provision
      ansible.builtin.include_tasks: provision.yml
      when: role_action == 'provision'

    - name: deprovision
      ansible.builtin.include_tasks: deprovision.yml
      run_once: true
      when: role_action == 'deprovision'
  always:
    - name: revoke the SSO token
      ovirt.ovirt.ovirt_auth:
        url: "{{ lookup('env', 'OVIRT_URL') | default(ovirt.url, true) }}"
        username: "{{ lookup('env', 'OVIRT_USERNAME') | default(ovirt.username, true) }}"
        password: "{{ lookup('env', 'OVIRT_PASSWORD') | default(ovirt.password, true) }}"
        insecure: true
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent
