---

- name: wait until the image is unlocked by the oVirt engine (<2.9)
  ovirt_disk_facts:
    auth: "{{ ovirt_auth }}"
    pattern: "name={{ _disk_name }}"
  until:
    - ovirt_disks is defined
    - ovirt_disks | length > 0
    - ovirt_disks | map(attribute='status') | difference(['locked']) | length == 0
  retries: 10
  delay: 3
  with_subelements:
    - "{{ nodes }}"
    - disks
    - skip_missing: true
  when:
    - nodes is defined
    - disks_creation.results is defined
    - item.1 is defined
  vars:
    _vm_name: "{{ item.0.name }}"
    _disk_auto_name: "{{ _vm_name }}_disk"
    _disk_name: "{{ item.1.name | default(_disk_auto_name) }}"
